using System;
using System.Collections.Generic;
using System.IO;
namespace Sudoku_Editor
{
    class Open
    {
        public static void Zen_of_Sudoku(string path)
        {
            BinaryReader br = new BinaryReader(File.OpenRead(path));
            br.ReadInt32();
            Form1.A1.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.A1Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.A2.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.A2Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.A3.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.A3Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.A4.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.A4Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.A5.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.A5Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.A6.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.A6Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.A7.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.A7Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.A8.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.A8Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.A9.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.B9Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.B1.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.B1Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.B2.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.B2Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.B3.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.B3Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.B4.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.B4Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.B5.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.B5Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.B6.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.B6Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.B7.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.B7Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.B8.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.B8Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.B9.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.B9Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.C1.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.C1Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.C2.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.C2Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.C3.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.C3Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.C4.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.C4Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.C5.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.C5Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.C6.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.C6Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.C7.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.C7Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.C8.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.C8Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.C9.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.C9Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.D1.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.D1Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.D2.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.D2Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.D3.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.D3Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.D4.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.D4Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.D5.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.D5Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.D6.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.D6Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.D7.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.D7Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.D8.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.D8Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.D9.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.D9Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.E1.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.E1Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.E2.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.E2Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.E3.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.E3Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.E4.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.E4Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.E5.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.E5Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.E6.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.E6Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.E7.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.E7Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.E8.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.E8Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.E9.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.F9Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.F1.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.F1Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.F2.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.F2Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.F3.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.F3Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.F4.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.F4Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.F5.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.F5Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.F6.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.F6Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.F7.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.F7Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.F8.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.F8Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.F9.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.F9Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.G1.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.G1Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.G2.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.G2Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.G3.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.G3Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.G4.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.G4Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.G5.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.G5Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.G6.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.G6Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.G7.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.G7Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.G8.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.G8Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.G9.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.G9Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.H1.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.H1Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.H2.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.H2Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.H3.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.H3Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.H4.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.H4Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.H5.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.H5Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.H6.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.H6Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.H7.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.H7Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.H8.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.H8Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.H9.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.H9Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.I1.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.I1Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.I2.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.I2Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.I3.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.I3Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.I4.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.I4Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.I5.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.I5Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.I6.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.I6Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.I7.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.I7Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.I8.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.I8Check.Checked = Convert.ToBoolean(br.ReadInt64());
            Form1.I9.Value = br.ReadInt64();
            br.ReadInt32();
            Form1.I9Check.Checked = Convert.ToBoolean(br.ReadInt64());
            br.Close();
        }

        public static void Super_Turbo_Sudoku(string path)
        {
            StreamReader sr = new StreamReader(File.OpenRead(path));
            sr.ReadLine();
            Form1.A1Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.A2Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.A3Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.A4Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.A5Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.A6Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.A7Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.A8Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.B9Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.B1Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.B2Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.B3Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.B4Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.B5Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.B6Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.B7Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.B8Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.B9Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.C1Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.C2Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.C3Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.C4Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.C5Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.C6Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.C7Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.C8Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.C9Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.D1Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.D2Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.D3Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.D4Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.D5Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.D6Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.D7Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.D8Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.D9Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.E1Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.E2Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.E3Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.E4Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.E5Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.E6Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.E7Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.E8Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.F9Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.F1Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.F2Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.F3Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.F4Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.F5Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.F6Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.F7Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.F8Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.F9Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.G1Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.G2Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.G3Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.G4Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.G5Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.G6Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.G7Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.G8Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.G9Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.H1Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.H2Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.H3Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.H4Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.H5Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.H6Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.H7Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.H8Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.H9Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.I1Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.I2Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.I3Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.I4Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.I5Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.I6Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.I7Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.I8Check.Checked = sr.Read() != '0';
            sr.Read();
            Form1.I9Check.Checked = sr.Read() != '0';
            sr.Read();
            sr.Read();
            Form1.A1.Value = sr.Read() - 48;
            sr.Read();            
            Form1.A2.Value = sr.Read() - 48;
            sr.Read();            
            Form1.A3.Value = sr.Read() - 48;
            sr.Read();            
            Form1.A4.Value = sr.Read() - 48;
            sr.Read();            
            Form1.A5.Value = sr.Read() - 48;
            sr.Read();            
            Form1.A6.Value = sr.Read() - 48;
            sr.Read();            
            Form1.A7.Value = sr.Read() - 48;
            sr.Read();            
            Form1.A8.Value = sr.Read() - 48;
            sr.Read();            
            Form1.A9.Value = sr.Read() - 48;
            sr.Read();            
            Form1.B1.Value = sr.Read() - 48;
            sr.Read();            
            Form1.B2.Value = sr.Read() - 48;
            sr.Read();            
            Form1.B3.Value = sr.Read() - 48;
            sr.Read();            
            Form1.B4.Value = sr.Read() - 48;
            sr.Read();            
            Form1.B5.Value = sr.Read() - 48;
            sr.Read();            
            Form1.B6.Value = sr.Read() - 48;
            sr.Read();            
            Form1.B7.Value = sr.Read() - 48;
            sr.Read();            
            Form1.B8.Value = sr.Read() - 48;
            sr.Read();            
            Form1.B9.Value = sr.Read() - 48;
            sr.Read();            
            Form1.C1.Value = sr.Read() - 48;
            sr.Read();            
            Form1.C2.Value = sr.Read() - 48;
            sr.Read();            
            Form1.C3.Value = sr.Read() - 48;
            sr.Read();            
            Form1.C4.Value = sr.Read() - 48;
            sr.Read();            
            Form1.C5.Value = sr.Read() - 48;
            sr.Read();            
            Form1.C6.Value = sr.Read() - 48;
            sr.Read();            
            Form1.C7.Value = sr.Read() - 48;
            sr.Read();            
            Form1.C8.Value = sr.Read() - 48;
            sr.Read();            
            Form1.C9.Value = sr.Read() - 48;
            sr.Read();            
            Form1.D1.Value = sr.Read() - 48;
            sr.Read();            
            Form1.D2.Value = sr.Read() - 48;
            sr.Read();            
            Form1.D3.Value = sr.Read() - 48;
            sr.Read();            
            Form1.D4.Value = sr.Read() - 48;
            sr.Read();            
            Form1.D5.Value = sr.Read() - 48;
            sr.Read();            
            Form1.D6.Value = sr.Read() - 48;
            sr.Read();            
            Form1.D7.Value = sr.Read() - 48;
            sr.Read();            
            Form1.D8.Value = sr.Read() - 48;
            sr.Read();            
            Form1.D9.Value = sr.Read() - 48;
            sr.Read();            
            Form1.E1.Value = sr.Read() - 48;
            sr.Read();            
            Form1.E2.Value = sr.Read() - 48;
            sr.Read();            
            Form1.E3.Value = sr.Read() - 48;
            sr.Read();            
            Form1.E4.Value = sr.Read() - 48;
            sr.Read();            
            Form1.E5.Value = sr.Read() - 48;
            sr.Read();            
            Form1.E6.Value = sr.Read() - 48;
            sr.Read();            
            Form1.E7.Value = sr.Read() - 48;
            sr.Read();            
            Form1.E8.Value = sr.Read() - 48;
            sr.Read();            
            Form1.E9.Value = sr.Read() - 48;
            sr.Read();            
            Form1.F1.Value = sr.Read() - 48;
            sr.Read();            
            Form1.F2.Value = sr.Read() - 48;
            sr.Read();            
            Form1.F3.Value = sr.Read() - 48;
            sr.Read();            
            Form1.F4.Value = sr.Read() - 48;
            sr.Read();            
            Form1.F5.Value = sr.Read() - 48;
            sr.Read();            
            Form1.F6.Value = sr.Read() - 48;
            sr.Read();            
            Form1.F7.Value = sr.Read() - 48;
            sr.Read();            
            Form1.F8.Value = sr.Read() - 48;
            sr.Read();            
            Form1.F9.Value = sr.Read() - 48;
            sr.Read();            
            Form1.G1.Value = sr.Read() - 48;
            sr.Read();            
            Form1.G2.Value = sr.Read() - 48;
            sr.Read();            
            Form1.G3.Value = sr.Read() - 48;
            sr.Read();            
            Form1.G4.Value = sr.Read() - 48;
            sr.Read();            
            Form1.G5.Value = sr.Read() - 48;
            sr.Read();            
            Form1.G6.Value = sr.Read() - 48;
            sr.Read();            
            Form1.G7.Value = sr.Read() - 48;
            sr.Read();            
            Form1.G8.Value = sr.Read() - 48;
            sr.Read();            
            Form1.G9.Value = sr.Read() - 48;
            sr.Read();            
            Form1.H1.Value = sr.Read() - 48;
            sr.Read();            
            Form1.H2.Value = sr.Read() - 48;
            sr.Read();            
            Form1.H3.Value = sr.Read() - 48;
            sr.Read();            
            Form1.H4.Value = sr.Read() - 48;
            sr.Read();            
            Form1.H5.Value = sr.Read() - 48;
            sr.Read();            
            Form1.H6.Value = sr.Read() - 48;
            sr.Read();            
            Form1.H7.Value = sr.Read() - 48;
            sr.Read();            
            Form1.H8.Value = sr.Read() - 48;
            sr.Read();            
            Form1.H9.Value = sr.Read() - 48;
            sr.Read();            
            Form1.I1.Value = sr.Read() - 48;
            sr.Read();            
            Form1.I2.Value = sr.Read() - 48;
            sr.Read();            
            Form1.I3.Value = sr.Read() - 48;
            sr.Read();            
            Form1.I4.Value = sr.Read() - 48;
            sr.Read();            
            Form1.I5.Value = sr.Read() - 48;
            sr.Read();            
            Form1.I6.Value = sr.Read() - 48;
            sr.Read();            
            Form1.I7.Value = sr.Read() - 48;
            sr.Read();            
            Form1.I8.Value = sr.Read() - 48;
            sr.Read();            
            Form1.I9.Value = sr.Read() - 48;
            sr.Close();
        }
    }
}
